### ISSUE TITLE
HAOS 2023.12.x can't add repo

### ISSUE THREAD

**Issue by Coder84619** [ChrisRomp/addon-ecowitt-proxy#19]
HAOS 2023.12.x is unable to add the repo: 

Cmd('git') failed due to: exit code(128) cmdline: git clone -v --recursive --depth=1 --shallow-submodules -- https://github.com/ChrisRomp/addon-ecowitt-proxy /data/addons/git/7dd6dd2c stderr: 'Cloning into '/data/addons/git/7dd6dd2c'... fatal: protocol ' https' is not supported '

Also fails using HTTP.

**Comment by ChrisRomp** [comment]
Just tested it on HA Yellow and it worked.  Looking at your error, there's some whitespace character preceding your URL which is why you see `' https' is not supported` (note the space before `https`).  Try pasting it into a text editor first and ensuring it's trimmed. It would also be good to see Home Assistant do a `trim()` function on that URL upon entry.

**Comment by Coder84619** [comment]
@ChrisRomp Yes, thank you! Didn't see that white space. I got the proxy configured, and the Ecowitt device in HA now has entities! Thanks!
